name: owm
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.3.0
  - torchvision=0.18.0
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - rasterio
  - geopandas
  - shapely
  - contextily
  - pillow
  - requests
  - tqdm
  - opencv
  - ipykernel
  - jupyterlab
  - pip
  - pip:
    - segmentation-models-pytorch
    - omniwatermask
